### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by gwyrwch** [gwyrwch/android-battleship#1]
- [x] Firebase

- [x] Authentication (using any auth provider (Google, social network, etc) or plain email-password pair)

- [x] battleship game logic

**Comment by gwyrwch** [comment]
- [x] Create a 'Battleship' game.

- [x] Two players should be able to participate in game from different devices.

- [x] Firebase or similar service should be used as back-end replacement.

- [x] Player can authenticate using any auth provider (Google, social network, etc) or plain email-password pair.

- [x] User 1 creates a game gives game ID to opponent.

- [x] Opponent (user 2) joins the game via given ID.

- [x] User 1 device acts as a server and is responsible for game state updates.

- [x] User 2 device subscribes to state changes in DB and updates interface.

- [x] It is possible to look through statistics of previous games in game menu.

**Comment by gwyrwch** [comment]
- [x] make only horizontal mode (no matter what the screen orientation is) == put this in manifest to each activity android:screenOrientation="landscape"

**Comment by gwyrwch** [comment]
- [x] bug with Stats Activity (it opens not only ones)

- [x] bug with 1 or 2 players connected when one player leaves the game 

- [x] maybe design fixes

- [x]  bug with connecting to the game; player can connect to the game which doesn't exist

- [x] ? game ids (cause first 5 symbols can be the same for different people. probability is small but...
